### ISSUE TITLE
PluginUnderTest broken under Windows

### ISSUE THREAD

**Issue by ianroberts** [GateNLP/gate-top#11]
https://github.com/GateNLP/gate-top/blob/f4da54647a68219ba4e73838bcdcc51ad9a80e0a/gate-plugin-test-utils/src/main/java/gate/test/GATEPluginTestCase.java#L137

The string in which we are replacing here is a native file path, but the `replace` assumes Unix file name conventions.  On Windows this means we insert

    <CLASS>foo\bar\Baz</CLASS>

instead of

    <CLASS>foo.bar.Baz</CLASS>

and loading the `PluginUnderTest` then fails with a `NoClassDefFoundError`

    java.lang.NoClassDefFoundError: com\example\SomePR (wrong name: com/example/SomePR)

**Comment by greenwoodma** [comment]
Damn. Sometimes I can be so stupid :(

Thanks for the fix.
