### ISSUE TITLE
May need to upgrade the versions of some of the maven plugins in plugin-base

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-top#15]
Did not look into this in detail, but I noticed that when I just rely on the "default" settings I am getting weird problems in the "mvn site" log and adding the maven compiler plugin, maven site plugin and other plugins with a more recent version eventually makes those problems go away. 

Need to figure out what exactly needs to get upgraded or changed.

**Comment by greenwoodma** [comment]
think this is now closed via 23449baaed7e589006778065ed3c9a5d036d4fa9
