### ISSUE TITLE
Upgrade gate-asm to a newer version

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gate-top#17]
We currently repackage gate-asm 6.1.1 but this doesn't support Java 11. We should probably upgrade this to use the latest version assuming it still supports Java 8 given that is still the minimum supported version of Java for GATE itself, and the one we use for building the distro.

**Comment by htseal** [comment]
How can I help to perform this update -  
I was thinking of creating a fork and making a pull request, is that a viable way forward?

**Comment by greenwoodma** [comment]
fixed by b80fb92ee50699bbf7ca15fc2dad42442c2726b4
