### ISSUE TITLE
should plugin pom.xml files reference our snapshot repo

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gate-top#6]
Currently none of the pom.xml files in our plugins include a reference to our snapshot repo. I think this should be changed so that a plugin can depend at compile time, if needed, on a snapshot version of another plugin without that plugin having to be manually installed into the users local maven cache.

We should also add the reference into the pom.xml in the archetype

**Comment by ianroberts** [comment]
While not a hard requirement, it is "discouraged" to have a `<repositories>` section in any POM that will be published to central (http://central.sonatype.org/pages/requirements.html).  Maybe one way to go would be to put the repository definition in SNAPSHOT versions of the plugin parent POM, but not in the release versions.  That way SNAPSHOT plugins based on the SNAPSHOT parent should be able to reference other SNAPSHOT plugins, but release versions would be forced to depend only on other releases.

**Comment by ianroberts** [comment]
Hmm, though you'd need to already have something (your plugin's own POM or your `~/.m2/settings.xml`) referring to our repo in order to be able to resolve the SNAPSHOT parent in the first place, which is something of a catch 22.

**Comment by greenwoodma** [comment]
I might add a commented out repository element to the archetype so people can uncomment and use if needed, but with a comment to say release versions shouldn't use the repo.

**Comment by greenwoodma** [comment]
We've never needed this in the last couple of years so I'm closing this issue
